FROM openjdk:19-jdk-slim
MAINTAINER Jade_Nofx
COPY target/delivery-0.0.1-SNAPSHOT.jar deliveryappdockerfile.jar     //sube el paquete a github
ENTRYPOINT ["java","-jar","/deliveryappdockerfile.jar"]     //instruccion a ejecutarse primero
